version: '3'

services:
  web:
    container_name: web_container
    build: 
      context: ./web
      dockerfile: Dockerfile
    environment:
      Z: "Asia/Tokyo"
    ports:
        - "8084:80"
    volumes:
      - type: bind
        source: ./app
        target: /var/www/html

# networks:

# volumes:
